### ISSUE TITLE
Use indexedDB how Storage

### ISSUE THREAD

**Issue by BlackRam-oss** [DRincs-Productions/pixi-vn#223]
Use indexDB for:

- [ ] NarrationManagerStatic._stepsHistory
- [ ] ~~StorageManagerStatic.store~~
- [ ] ~~SoundManagerStatic.playInStepIndex~~
- [ ] ~~StoredClassModel~~

If indexedDB is supported by default you should use indexedDB: https://stackoverflow.com/questions/34496096/how-to-detect-if-indexeddb-is-enabled

Add the ability to choose whether to use ram or indexedDB (cannot easily modify items saved in ram)

**Comment by blurymind** [comment]
I wrote a little module to do this in yarnclassic inside storage.js
It seems to work well, but unlike localstorage its async. So you have to do async await and then... kind of chaining

**Comment by BlackRam-oss** [comment]
yeah, it definitely needs to be used in saves, but this change will be made in the template.

I didn't know it was asynchronous. If I insert it in these functions https://pixi-vn.web.app/start/storage.html, they will have to be used asynchronously. This doesn't drive me crazy.
But the pro is that (based on the developer's choice) instead of having values ​​in the ram, I would have them in a db that can be inspected not by the browser by the player.

**Comment by BlackRam-oss** [comment]
thinking about it I often use "Property getters and setters" to get values ​​in storage.
so I can't use async in there.

so I can use indexDB sulo to save the history of the steps.
